HW1
ok-technopolis-autumn-2022/Emelyanov_Vitaliy pull request #1
Opened 2022-09-29 15:50 UTC by GenryEden

2022-09-29 16:15 UTC, fromanywhere requested changes
Неплохое начало, но есть типовые грабли

2022-09-29 16:15 UTC, fromanywhere commented on main.html
> +        <title>Test</title>
Может оказаться вот так https://welovehtml.ru/charset/example.html

2022-09-29 16:15 UTC, fromanywhere commented on main.html
> +<html lang="en">
Действительно ли аудитория Вашего приложения будет использовать английский язык?

2022-09-29 16:15 UTC, fromanywhere commented on main.html
> +                <div class="todo-thing">
Здесь лучше подумать над использованием других тегов

2022-09-29 16:15 UTC, fromanywhere commented on main.html
> +                    HTML
Потерялось удаление

2022-09-29 16:15 UTC, fromanywhere commented on main.html
> +                <input type="button" value="↓" class="hider-button">
Можно просто <button

2022-10-03 22:22 UTC, GenryEden commented
* Удален Unicode символ со стрелкой вниз из скобки, заменен на "Check all"
* Список задач был реализован на тегах ненумерованного списка
* Добавлена кнопка удаления поля
* Добавлено скрытое поле ввода для будущего редактирования задач
* Все input с классом button заменены на соответствующие теги

2022-10-03 22:50 UTC, GenryEden commented
По поводу языка было принято решение разместиться на двух стульях в соответствии с [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#accessibility) (см. пункт Accessibility и ссылку на WCAG Success Criterion 3.1.2). Для всего документа язык английский, для списка русский, для кнопок удаления (которые по html находятся внутри списка) - английский.

2022-10-05 10:24 UTC, fromanywhere requested changes

2022-10-05 10:24 UTC, fromanywhere commented on main.html
> +                    <button class="active-button">
В лекции договорились сделать это радиокнопками

2022-10-05 10:24 UTC, fromanywhere commented on main.html
> +                    <input class="edit-todo-thing" value="HTML" hidden="hidden">
Но формы же всё равно нет, зачем?

2022-10-07 19:18 UTC, GenryEden commented on main.html
> +                    <input class="edit-todo-thing" value="HTML" hidden="hidden">
завернуть инпут в форму или вообще удалить?

2022-10-08 11:18 UTC, fromanywhere commented on main.html
> +                    <input class="edit-todo-thing" value="HTML" hidden="hidden">
предлагаю удалить

2022-10-10 09:00 UTC, fromanywhere requested changes

2022-10-10 09:00 UTC, fromanywhere commented on main.html
> +        <title>Test</title>
поэтому нужно всегда нужно писать кодировку явно

2022-10-10 09:00 UTC, fromanywhere commented on main.html
> +                <span class="selector">
здесь лучше написать role и к ней заголовок в aria-label

2022-10-11 07:53 UTC, fromanywhere approved these changes

2022-10-16 16:15 UTC, merged