Js
ok-technopolis-autumn-2022/Emelyanov_Vitaliy pull request #4
Opened 2022-11-23 10:17 UTC by GenryEden

2022-11-23 10:41 UTC, fromanywhere requested changes

2022-11-23 10:41 UTC, fromanywhere commented on index.js
> +  selector.addEventListener("click", changeFilter);
Навешивать обработчики в цикле неспортивно. Давайте сделаем делегирование

2022-11-23 10:41 UTC, fromanywhere commented on index.js
> +  ans.addEventListener("click", remarkToDo);
Здесь тоже получается, что на каждый чекбокс свой обработчик. Давайте избавимся от этого

2022-11-25 14:34 UTC, fromanywhere approved these changes

2022-11-25 14:34 UTC, fromanywhere commented on index.js
> +  console.log(e.target.nodeName)
забытая отладка

2022-11-25 14:34 UTC, fromanywhere commented on index.js
> +let todos = [];
const

2022-11-25 14:34 UTC, fromanywhere commented on index.js
> +  if (e.target.nodeName != "INPUT") {
здесь лучше по имени класса

2022-11-25 14:34 UTC, fromanywhere commented on index.js
> +  ans.setAttribute("class", "delete-button");
className?

2022-11-26 19:46 UTC, GenryEden commented on index.js
> +let todos = [];
в дальнейшем она изменяется с помощью filter

2022-11-27 14:21 UTC, merged